const _ = 'ev_last_stand_ui_quantum_switch_forward',
    a = 'ev_last_stand_ui_quantum_switch_backward',
    s = 'ev_last_stand_ui_quantum_switch_auto',
    t = 'ev_last_stand_reward_screen_icon',
    e = 'ev_last_stand_reward_screen_icon',
    n = 'ev_last_stand_pbs_screen_points_start',
    i = 'ev_last_stand_pbs_screen_points_end',
    d = 'ev_last_stand_reward_screen_icon',
    r = 'ev_last_stand_info_objectives_item',
    l = 'ev_last_stand_reward_path_quantum_icon_anim',
    c = 'ev_last_stand_reward_path_rewards_icon_anim',
    h = 'ev_last_stand_ui_chapter_highlight',
    o = 'ev_last_stand_ui_chapter_01',
    v = 'ev_last_stand_ui_chapter_02',
    u = 'ev_last_stand_ui_chapter_03',
    p = 'ev_last_stand_ui_shop_keys_highlight_on',
    w = 'ev_last_stand_ui_shop_keys_highlight_off',
    m = 'ev_last_stand_ui_shop_keys_anim',
    g = 'ev_last_stand_ui_hotkey_switch',
    k = 'ev_last_stand_promo_screen_enter',
    b = 'ev_last_stand_promo_screen_exit';
export {
    g as A,
    h as D,
    e as K,
    a as M,
    n as P,
    l as Q,
    i as a,
    d as b,
    o as c,
    v as d,
    u as e,
    _ as f,
    s as g,
    t as h,
    r as i,
    b as j,
    k,
    c as l,
    m,
    p as n,
    w as o,
};
